### ISSUE TITLE
Sticky Table Reload in EDGE While Inspecting the content in table

### ISSUE THREAD

**Issue by Sudeep2443** [armaaar/JQuery-Sticky-Table#6]
@armaaar I have found another new issue in your demo, While i am using the Edge Browser, i inspect the content and found the the page get reloaded again and again.

Here is small video for the reference of issue arise:
https://www.screencast.com/t/uIZDePAji

Please let me know if you found the same and the solution for it.

**Comment by armaaar** [comment]
Sorry for late response as I'm not available most of the time.
For sorry this is a bug in Microsoft Edge with any element using 'position:sticky' that is not related to the plugin itself. I tried to use JS to simulate the same behavior of 'position:sticky' but it introduces a lag because of the asynchronous nature of how scroll event is implemented on edge.

I'm sorry but there is nothing for me to do here but wait for Edge team to fix the bug.
